### ISSUE TITLE
[Feature request] Please add a license to this project

### ISSUE THREAD

**Issue by MuTsunTsai** [apacheli/web-workers-polyfill#1]
This is a pretty good project and works as intended, but the problem is that it doesn't have any license, which means that, legally speaking, nobody else can use this code without your explicit permission. For people to be able to actually use it in production, it needs to have a license such as MIT. Please add it! Thanks.

**Comment by apacheli** [comment]
I had abandoned this project, but I can still see many people (including myself) still need a decent polyfill. Thanks for reawakening this project!

**Comment by broman** [comment]
Thanks apacheli! I would love to use this repository for all my polyfill needs!

**Comment by apacheli** [comment]
I've release [v2.0.0](https://www.npmjs.com/package/@apacheli/web-workers) which comes with a license alongside a few general code improvements.

**Comment by broman** [comment]
Oh heck yeah! Nice!
